In [8]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.options.display.max_rows = 8

In [9]:
df = pd.read_csv("data/vaccini.csv")

In [10]:
df.head(10)

,data_somministrazione,fornitore,area,fascia_anagrafica,sesso_maschile,sesso_femminile,categoria_operatori_sanitari_sociosanitari,categoria_personale_non_sanitario,categoria_ospiti_rsa,categoria_60_69,...,categoria_forze_armate,categoria_personale_scolastico,categoria_soggetti_fragili,categoria_altro,prima_dose,seconda_dose,codice_NUTS1,codice_NUTS2,codice_regione_ISTAT,nome_area
0,2020-12-27,Pfizer/BioNTech,ABR,20-29,1,0,1,0,0,0,...,0,0,0,0,1,0,ITF,ITF1,13,Abruzzo
1,2020-12-27,Pfizer/BioNTech,ABR,30-39,1,3,4,0,0,0,...,0,0,0,0,4,0,ITF,ITF1,13,Abruzzo
2,2020-12-27,Pfizer/BioNTech,ABR,40-49,1,6,7,0,0,0,...,0,0,0,0,7,0,ITF,ITF1,13,Abruzzo
3,2020-12-27,Pfizer/BioNTech,ABR,50-59,4,5,9,0,0,0,...,0,0,0,0,9,0,ITF,ITF1,13,Abruzzo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,2020-12-27,Pfizer/BioNTech,ABR,80-89,1,0,0,0,1,0,...,0,0,0,0,1,0,ITF,ITF1,13,Abruzzo
7,2020-12-27,Pfizer/BioNTech,BAS,20-29,4,5,9,0,0,0,...,0,0,0,0,9,0,ITF,ITF5,17,Basilicata
8,2020-12-27,Pfizer/BioNTech,BAS,30-39,10,18,27,0,0,0,...,0,0,0,1,28,0,ITF,ITF5,17,Basilicata
9,2020-12-27,Pfizer/BioNTech,BAS,40-49,7,23,29,0,0,0,...,0,0,0,1,30,0,ITF,ITF5,17,Basilicata

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37059 entries, 0 to 37058
Data columns (total 22 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   data_somministrazione                       37059 non-null  object
 1   fornitore                                   37059 non-null  object
 2   area                                        37059 non-null  object
 3   fascia_anagrafica                           37059 non-null  object
 4   sesso_maschile                              37059 non-null  int64
 5   sesso_femminile                             37059 non-null  int64
 6   categoria_operatori_sanitari_sociosanitari  37059 non-null  int64
 7   categoria_personale_non_sanitario           37059 non-null  int64
 8   categoria_ospiti_rsa                        37059 non-null  int64
 9   categoria_60_69                             37059 non-null  int64
 10  categoria_70_79                             37059 non-null  int64
 11  categoria_over80                            37059 non-null  int64
 12  categoria_forze_armate                      37059 non-null  int64
 13  categoria_personale_scolastico              37059 non-null  int64
 14  categoria_soggetti_fragili                  37059 non-null  int64
 15  categoria_altro                             37059 non-null  int64
 16  prima_dose                                  37059 non-null  int64
 17  seconda_dose                                37059 non-null  int64
 18  codice_NUTS1                                37059 non-null  object
 19  codice_NUTS2                                37059 non-null  object
 20  codice_regione_ISTAT                        37059 non-null  int64
 21  nome_area                                   37059 non-null  object
dtypes: int64(15), object(7)
memory usage: 6.2+ MB

In [15]:
df.count()

data_somministrazione    37059
fornitore                37059
area                     37059
fascia_anagrafica        37059
                         ...
codice_NUTS1             37059
codice_NUTS2             37059
codice_regione_ISTAT     37059
nome_area                37059
Length: 22, dtype: int64

In [18]:
df[['sesso_maschile', 'sesso_femminile']]

       sesso_maschile  sesso_femminile
0                   1                0
1                   1                3
2                   1                6
3                   4                5
...               ...              ...
37055              16               14
37056              73              127
37057               2                0
37058               2                3

[37059 rows x 2 columns]

In [21]:
df[19:30]

,data_somministrazione,fornitore,area,fascia_anagrafica,sesso_maschile,sesso_femminile,categoria_operatori_sanitari_sociosanitari,categoria_personale_non_sanitario,categoria_ospiti_rsa,categoria_60_69,...,categoria_forze_armate,categoria_personale_scolastico,categoria_soggetti_fragili,categoria_altro,prima_dose,seconda_dose,codice_NUTS1,codice_NUTS2,codice_regione_ISTAT,nome_area
19,2020-12-27,Pfizer/BioNTech,CAM,40-49,80,87,164,3,0,0,...,0,0,0,0,167,0,ITF,ITF3,15,Campania
20,2020-12-27,Pfizer/BioNTech,CAM,50-59,119,77,187,8,0,0,...,0,0,0,1,196,0,ITF,ITF3,15,Campania
21,2020-12-27,Pfizer/BioNTech,CAM,60-69,130,37,167,0,0,0,...,0,0,0,0,167,0,ITF,ITF3,15,Campania
22,2020-12-27,Pfizer/BioNTech,CAM,70-79,5,0,4,0,0,0,...,0,0,0,0,5,0,ITF,ITF3,15,Campania
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,2020-12-27,Pfizer/BioNTech,EMR,50-59,70,217,259,3,0,0,...,0,0,0,25,287,0,ITH,ITH5,8,Emilia-Romagna
27,2020-12-27,Pfizer/BioNTech,EMR,60-69,99,51,123,0,3,24,...,0,0,0,0,150,0,ITH,ITH5,8,Emilia-Romagna
28,2020-12-27,Pfizer/BioNTech,EMR,70-79,10,3,3,1,8,0,...,0,0,0,0,13,0,ITH,ITH5,8,Emilia-Romagna
29,2020-12-27,Pfizer/BioNTech,EMR,80-89,2,6,0,0,8,0,...,0,0,0,0,8,0,ITH,ITH5,8,Emilia-Romagna

In [24]:
df.loc[df['nome_area'] == 'Lombardia']

,data_somministrazione,fornitore,area,fascia_anagrafica,sesso_maschile,sesso_femminile,categoria_operatori_sanitari_sociosanitari,categoria_personale_non_sanitario,categoria_ospiti_rsa,categoria_60_69,...,categoria_forze_armate,categoria_personale_scolastico,categoria_soggetti_fragili,categoria_altro,prima_dose,seconda_dose,codice_NUTS1,codice_NUTS2,codice_regione_ISTAT,nome_area
50,2020-12-27,Pfizer/BioNTech,LOM,20-29,20,22,35,6,0,0,...,0,0,0,1,42,0,ITC,ITC4,3,Lombardia
51,2020-12-27,Pfizer/BioNTech,LOM,30-39,31,33,57,3,0,0,...,0,0,0,4,64,0,ITC,ITC4,3,Lombardia
52,2020-12-27,Pfizer/BioNTech,LOM,40-49,62,80,119,14,0,0,...,0,0,1,8,142,0,ITC,ITC4,3,Lombardia
53,2020-12-27,Pfizer/BioNTech,LOM,50-59,114,119,212,14,0,0,...,0,0,0,7,233,0,ITC,ITC4,3,Lombardia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37000,2021-04-19,Vaxzevria (AstraZeneca),LOM,60-69,1345,1605,66,4,2,2547,...,12,11,307,1,2949,1,ITC,ITC4,3,Lombardia
37001,2021-04-19,Vaxzevria (AstraZeneca),LOM,70-79,11936,14549,13,1,13,0,...,67,1,293,1,26484,1,ITC,ITC4,3,Lombardia
37002,2021-04-19,Vaxzevria (AstraZeneca),LOM,80-89,140,217,0,0,9,0,...,0,0,1,0,357,0,ITC,ITC4,3,Lombardia
37003,2021-04-19,Vaxzevria (AstraZeneca),LOM,90+,15,34,0,0,6,0,...,0,0,1,0,49,0,ITC,ITC4,3,Lombardia

In [28]:
array = ['Lombardia', 'Piemonte']
df.loc[df['nome_area'].isin(array)]

,data_somministrazione,fornitore,area,fascia_anagrafica,sesso_maschile,sesso_femminile,categoria_operatori_sanitari_sociosanitari,categoria_personale_non_sanitario,categoria_ospiti_rsa,categoria_60_69,...,categoria_forze_armate,categoria_personale_scolastico,categoria_soggetti_fragili,categoria_altro,prima_dose,seconda_dose,codice_NUTS1,codice_NUTS2,codice_regione_ISTAT,nome_area
50,2020-12-27,Pfizer/BioNTech,LOM,20-29,20,22,35,6,0,0,...,0,0,0,1,42,0,ITC,ITC4,3,Lombardia
51,2020-12-27,Pfizer/BioNTech,LOM,30-39,31,33,57,3,0,0,...,0,0,0,4,64,0,ITC,ITC4,3,Lombardia
52,2020-12-27,Pfizer/BioNTech,LOM,40-49,62,80,119,14,0,0,...,0,0,1,8,142,0,ITC,ITC4,3,Lombardia
53,2020-12-27,Pfizer/BioNTech,LOM,50-59,114,119,212,14,0,0,...,0,0,0,7,233,0,ITC,ITC4,3,Lombardia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37020,2021-04-19,Vaxzevria (AstraZeneca),PIE,50-59,3,5,0,1,0,0,...,0,0,7,0,8,0,ITC,ITC1,1,Piemonte
37021,2021-04-19,Vaxzevria (AstraZeneca),PIE,60-69,303,368,2,5,0,539,...,0,0,125,0,671,0,ITC,ITC1,1,Piemonte
37022,2021-04-19,Vaxzevria (AstraZeneca),PIE,70-79,2119,2477,0,0,0,0,...,0,0,131,0,4589,7,ITC,ITC1,1,Piemonte
37023,2021-04-19,Vaxzevria (AstraZeneca),PIE,80-89,3,1,0,0,0,0,...,0,0,0,0,4,0,ITC,ITC1,1,Piemonte

In [31]:
df.loc[df['sesso_maschile'] > 100]

,data_somministrazione,fornitore,area,fascia_anagrafica,sesso_maschile,sesso_femminile,categoria_operatori_sanitari_sociosanitari,categoria_personale_non_sanitario,categoria_ospiti_rsa,categoria_60_69,...,categoria_forze_armate,categoria_personale_scolastico,categoria_soggetti_fragili,categoria_altro,prima_dose,seconda_dose,codice_NUTS1,codice_NUTS2,codice_regione_ISTAT,nome_area
20,2020-12-27,Pfizer/BioNTech,CAM,50-59,119,77,187,8,0,0,...,0,0,0,1,196,0,ITF,ITF3,15,Campania
21,2020-12-27,Pfizer/BioNTech,CAM,60-69,130,37,167,0,0,0,...,0,0,0,0,167,0,ITF,ITF3,15,Campania
53,2020-12-27,Pfizer/BioNTech,LOM,50-59,114,119,212,14,0,0,...,0,0,0,7,233,0,ITC,ITC4,3,Lombardia
54,2020-12-27,Pfizer/BioNTech,LOM,60-69,160,41,180,6,2,13,...,0,0,0,0,201,0,ITC,ITC4,3,Lombardia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37037,2021-04-19,Vaxzevria (AstraZeneca),SAR,70-79,1164,1277,0,0,0,0,...,0,0,2,3,2439,2,ITG,ITG2,20,Sardegna
37042,2021-04-19,Vaxzevria (AstraZeneca),SIC,60-69,291,344,2,2,2,591,...,0,1,37,0,635,0,ITG,ITG1,19,Sicilia
37043,2021-04-19,Vaxzevria (AstraZeneca),SIC,70-79,313,352,0,0,0,0,...,0,0,27,0,665,0,ITG,ITG1,19,Sicilia
37048,2021-04-19,Vaxzevria (AstraZeneca),UMB,70-79,260,292,0,0,0,0,...,0,0,0,0,552,0,ITI,ITI2,10,Umbria

In [33]:
df.loc[df['sesso_maschile'] + df["sesso_femminile"] > 200]

,data_somministrazione,fornitore,area,fascia_anagrafica,sesso_maschile,sesso_femminile,categoria_operatori_sanitari_sociosanitari,categoria_personale_non_sanitario,categoria_ospiti_rsa,categoria_60_69,...,categoria_forze_armate,categoria_personale_scolastico,categoria_soggetti_fragili,categoria_altro,prima_dose,seconda_dose,codice_NUTS1,codice_NUTS2,codice_regione_ISTAT,nome_area
25,2020-12-27,Pfizer/BioNTech,EMR,40-49,80,146,199,1,1,0,...,0,0,0,25,226,0,ITH,ITH5,8,Emilia-Romagna
26,2020-12-27,Pfizer/BioNTech,EMR,50-59,70,217,259,3,0,0,...,0,0,0,25,287,0,ITH,ITH5,8,Emilia-Romagna
53,2020-12-27,Pfizer/BioNTech,LOM,50-59,114,119,212,14,0,0,...,0,0,0,7,233,0,ITC,ITC4,3,Lombardia
54,2020-12-27,Pfizer/BioNTech,LOM,60-69,160,41,180,6,2,13,...,0,0,0,0,201,0,ITC,ITC4,3,Lombardia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37037,2021-04-19,Vaxzevria (AstraZeneca),SAR,70-79,1164,1277,0,0,0,0,...,0,0,2,3,2439,2,ITG,ITG2,20,Sardegna
37042,2021-04-19,Vaxzevria (AstraZeneca),SIC,60-69,291,344,2,2,2,591,...,0,1,37,0,635,0,ITG,ITG1,19,Sicilia
37043,2021-04-19,Vaxzevria (AstraZeneca),SIC,70-79,313,352,0,0,0,0,...,0,0,27,0,665,0,ITG,ITG1,19,Sicilia
37048,2021-04-19,Vaxzevria (AstraZeneca),UMB,70-79,260,292,0,0,0,0,...,0,0,0,0,552,0,ITI,ITI2,10,Umbria

In [40]:
media = df['sesso_maschile'].mean() + df["sesso_femminile"].mean()
df.loc[df['sesso_maschile'] + df["sesso_femminile"] > media]

,data_somministrazione,fornitore,area,fascia_anagrafica,sesso_maschile,sesso_femminile,categoria_operatori_sanitari_sociosanitari,categoria_personale_non_sanitario,categoria_ospiti_rsa,categoria_60_69,...,categoria_forze_armate,categoria_personale_scolastico,categoria_soggetti_fragili,categoria_altro,prima_dose,seconda_dose,codice_NUTS1,codice_NUTS2,codice_regione_ISTAT,nome_area
216,2020-12-30,Pfizer/BioNTech,LAZ,40-49,147,294,441,0,0,0,...,0,0,0,0,441,0,ITI,ITI4,12,Lazio
217,2020-12-30,Pfizer/BioNTech,LAZ,50-59,156,280,435,0,1,0,...,0,0,0,0,436,0,ITI,ITI4,12,Lazio
282,2020-12-31,Pfizer/BioNTech,CAM,50-59,231,191,359,48,1,0,...,0,0,0,14,422,0,ITF,ITF3,15,Campania
288,2020-12-31,Pfizer/BioNTech,EMR,40-49,149,309,389,33,5,0,...,0,0,0,31,458,0,ITH,ITH5,8,Emilia-Romagna
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37037,2021-04-19,Vaxzevria (AstraZeneca),SAR,70-79,1164,1277,0,0,0,0,...,0,0,2,3,2439,2,ITG,ITG2,20,Sardegna
37042,2021-04-19,Vaxzevria (AstraZeneca),SIC,60-69,291,344,2,2,2,591,...,0,1,37,0,635,0,ITG,ITG1,19,Sicilia
37043,2021-04-19,Vaxzevria (AstraZeneca),SIC,70-79,313,352,0,0,0,0,...,0,0,27,0,665,0,ITG,ITG1,19,Sicilia
37048,2021-04-19,Vaxzevria (AstraZeneca),UMB,70-79,260,292,0,0,0,0,...,0,0,0,0,552,0,ITI,ITI2,10,Umbria

In [50]:
df['sesso_maschile'].sum() + df["sesso_femminile"].sum()

15558775

In [81]:
df.groupby('nome_area')[['sesso_maschile']].sum()

                                sesso_maschile
nome_area
Abruzzo                                 144680
Basilicata                               58529
Calabria                                193580
Campania                                609533
...                                        ...
Toscana                                 408671
Umbria                                   99024
Valle d'Aosta / VallÃ©e d'Aoste           15044
Veneto                                  537404

[21 rows x 1 columns]

In [84]:
sum_column = df["sesso_maschile"] + df["sesso_femminile"]
df["total"] = sum_column
df.groupby('nome_area')[['total']].sum()

                                  total
nome_area
Abruzzo                          344043
Basilicata                       135940
Calabria                         406187
Campania                        1333116
...                                 ...
Toscana                         1015018
Umbria                           241787
Valle d'Aosta / VallÃ©e d'Aoste    35033
Veneto                          1330197

[21 rows x 1 columns]

In [85]:
total = df['sesso_maschile'].sum() + df["sesso_femminile"].sum()
df.groupby('nome_area')[['total']].sum() / total * 100

                                   total
nome_area
Abruzzo                         2.211247
Basilicata                      0.873719
Calabria                        2.610662
Campania                        8.568258
...                                  ...
Toscana                         6.523766
Umbria                          1.554023
Valle d'Aosta / VallÃ©e d'Aoste  0.225166
Veneto                          8.549497

[21 rows x 1 columns]

In [87]:
reg = df.groupby('nome_area')[['total']].sum()
print(reg > 100000)

                                total
nome_area
Abruzzo                          True
Basilicata                       True
Calabria                         True
Campania                         True
...                               ...
Toscana                          True
Umbria                           True
Valle d'Aosta / VallÃ©e d'Aoste  False
Veneto                           True

[21 rows x 1 columns]